server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: vendorcorp-core
      alb.ingress.kubernetes.io/scheme: internal
  persistentVolume:
    storageClass: efs-fs
  service:
    type: NodePort

alertmanager:
  persistence:
    storageClass: efs-fs